sudo: false
language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - npm install

script:
  - npm test

after_success:
  - cat ./coverage/unit/lcov.info|./node_modules/.bin/coveralls
